name: 🔐 Azure Login Test

on:
  workflow_dispatch:

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure using AZURE_CREDENTIALS
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current Azure subscription (debug)
        run: az account show
